<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Company>zaprett-openwrt</Company>
    <Product>zaprett for Windows</Product>
    <Version>0.1.1</Version>
    <Copyright>MIT License</Copyright>
  </PropertyGroup>
</Project>
