<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>zaprett-svc</AssemblyName>
    <RootNamespace>Zaprett.Service</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UserSecretsId>dotnet-Zaprett.Service-5cf671c9-3341-4101-901e-3912f00ff0c6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zaprett.Service.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zaprett.Core\Zaprett.Core.csproj" />
    <ProjectReference Include="..\Zaprett.Ipc\Zaprett.Ipc.csproj" />
  </ItemGroup>
</Project>
