namespace Zaprett.Core.Text;

/// <summary>Resource table of the core: key → ru / en / zh-CN. Whole sentences only (no phrase gluing); data goes into
/// {0}, {1}... Chinese terms follow windows/docs/GLOSSARY-zh.md (策略 strategy, 列表 list, 订阅 subscription, 引擎 engine,
/// 绕过 bypass, 自动选择 automatic selection, 监控 monitor, 看门狗 watchdog, 预设 preset, 任务 job, 仓库 repository).</summary>
public static class Strings
{
    static T.Entry E(string ru, string en, string zh) => new(ru, en, zh);

    public static readonly IReadOnlyDictionary<string, T.Entry> Table = new Dictionary<string, T.Entry>(StringComparer.Ordinal)
    {
        /* ---------- dispatcher, arguments, rights ---------- */
        ["call.unknown_method"] = E("Неизвестный метод «{0}»", "Unknown method \"{0}\"", "未知方法“{0}”"),
        ["call.access_denied"] = E(
            "Недостаточно прав: изменять настройки и управлять службой могут администраторы и группа zaprett Operators",
            "Not enough rights: only administrators and the zaprett Operators group can change settings and control the service",
            "权限不足：只有管理员和 zaprett Operators 组可以更改设置和控制服务"),
        ["call.admin_only"] = E(
            "Это действие доступно только администраторам: оно может запустить чужой код от имени службы",
            "Only administrators can do this: it may run third-party code as the service",
            "只有管理员可以执行此操作：它可能以服务身份运行第三方代码"),
        ["call.cancelled"] = E("Запрос отменён", "The request was cancelled", "请求已取消"),
        ["call.internal_error"] = E("Внутренняя ошибка: {0}", "Internal error: {0}", "内部错误：{0}"),
        ["call.bad_lang"] = E("Язык: ru, en или zh-CN", "Language: ru, en or zh-CN", "语言：ru、en 或 zh-CN"),
        ["arg.must_be_string"] = E("Аргумент «{0}» должен быть строкой", "Argument \"{0}\" must be a string", "参数“{0}”必须是字符串"),
        ["arg.missing"] = E("Не указан аргумент «{0}»", "Argument \"{0}\" is missing", "缺少参数“{0}”"),
        ["arg.string_array"] = E("Аргумент «{0}»: ожидается массив строк", "Argument \"{0}\": an array of strings is expected", "参数“{0}”：应为字符串数组"),
        ["arg.must_be_bool"] = E("Аргумент «{0}» должен быть true или false", "Argument \"{0}\" must be true or false",
            "参数“{0}”必须为 true 或 false"),
        ["arg.must_be_number"] = E("Аргумент «{0}» должен быть числом", "Argument \"{0}\" must be a number", "参数“{0}”必须是数字"),
        ["log.event_handler"] = E("обработчик события {0}: {1}", "event handler {0}: {1}", "事件处理程序 {0}：{1}"),
        ["log.test_recovered"] = E("автоподбор прервался аварийно: исходная стратегия возвращена",
            "the automatic selection was interrupted: the original strategy is back", "自动选择意外中断：已恢复原来的策略"),

        /* ---------- service control ---------- */
        ["svc.test_running_wait"] = E("Идёт автоподбор стратегии. Дождитесь окончания или остановите его.",
            "An automatic strategy selection is running. Wait for it to finish or stop it.", "正在自动选择策略。请等待其完成或停止它。"),
        ["svc.test_running_stop"] = E("Идёт автоподбор стратегии. Остановите его (test.stop).",
            "An automatic strategy selection is running. Stop it first (test.stop).", "正在自动选择策略。请先停止它（test.stop）。"),
        ["svc.test_running"] = E("Идёт автоподбор стратегии.", "An automatic strategy selection is running.", "正在自动选择策略。"),
        ["svc.save_enabled_failed"] = E("Не удалось сохранить настройку enabled", "Could not save the setting enabled", "无法保存 enabled 设置"),
        ["svc.stop_failed"] = E("Не удалось остановить движок", "Could not stop the engine", "无法停止引擎"),
        ["svc.disabled"] = E("Служба выключена. Включите и запустите её (start).", "The service is disabled. Enable and start it (start).",
            "服务已禁用。请启用并启动它（start）。"),
        ["svc.engine_not_running"] = E("Движок не запустился. Подробности — в журнале (zaprett log).",
            "The engine did not start. See the log for details (zaprett log).", "引擎未能启动。详情请查看日志（zaprett log）。"),
        ["svc.dry_run_failed"] = E("Движок отклонил аргументы стратегии: {0}", "The engine rejected the strategy arguments: {0}",
            "引擎拒绝了策略参数：{0}"),
        ["log.dry_run_failed"] = E("проверка аргументов {0} (стратегия {1}) не прошла, код {2}: {3}",
            "argument check of {0} (strategy {1}) failed, code {2}: {3}", "{0} 的参数检查（策略 {1}）未通过，代码 {2}：{3}"),
        ["svc.engine_exe_missing"] = E("Не найден исполняемый файл движка {0}", "Engine executable not found: {0}", "未找到引擎可执行文件：{0}"),
        ["svc.engine_missing"] = E("Движок {0} не установлен", "Engine {0} is not installed", "引擎 {0} 未安装"),
        ["svc.engine_missing_component"] = E("Движок {0} не установлен (компонент программы)", "Engine {0} is not installed (a program component)",
            "引擎 {0} 未安装（程序组件）"),
        ["svc.save_settings_failed"] = E("Не удалось сохранить настройки", "Could not save the settings", "无法保存设置"),
        ["svc.bad_values"] = E("Неверные значения: {0}", "Invalid values: {0}", "无效的值：{0}"),
        ["svc.save_dns_failed"] = E("Не удалось сохранить dns.mode", "Could not save dns.mode", "无法保存 dns.mode"),
        ["svc.update_not_supported"] = E("Обновление программы недоступно в этой сборке", "Program updates are not available in this build",
            "此版本不提供程序更新"),
        ["svc.bad_channel"] = E("Канал обновлений: stable или beta", "Update channel: stable or beta", "更新通道：stable 或 beta"),
        ["svc.bad_tail"] = E("tail: целое число от 1", "tail: a whole number from 1", "tail：从 1 开始的整数"),
        ["svc.bad_page"] = E("Страница: overview, lists, strategies или diagnostics", "Page: overview, lists, strategies or diagnostics",
            "页面：overview、lists、strategies 或 diagnostics"),
        ["svc.bad_page_part"] = E("неизвестная часть страницы", "unknown page part", "未知的页面部分"),
        ["svc.engine_version_failed"] = E("версия {0}: {1}", "version of {0}: {1}", "{0} 版本：{1}"),
        ["svc.debug_expired"] = E("отладка движка выключена: истекло время ({0} мин)", "engine debugging switched off: its time is up ({0} min)",
            "引擎调试已关闭：时间已到（{0} 分钟）"),

        /* ---------- diagnostic report ---------- */
        ["diag.not_installed"] = E("не установлен", "not installed", "未安装"),
        ["diag.none"] = E("(нет)", "(none)", "（无）"),
        ["diag.system"] = E("Система", "System", "系统"),
        ["diag.status"] = E("Состояние", "Status", "状态"),
        ["diag.args"] = E("Аргументы движка", "Engine arguments", "引擎参数"),
        ["diag.generate"] = E("Результат генерации", "Generation result", "生成结果"),
        ["diag.conflicts"] = E("Конфликты", "Conflicts", "冲突"),
        ["diag.job"] = E("Фоновая задача", "Background job", "后台任务"),
        ["diag.log"] = E("Журнал (последние {0} строк)", "Log (last {0} lines)", "日志（最后 {0} 行）"),

        /* ---------- items, lists, strategies ---------- */
        ["items.bad_type"] = E("Неизвестный тип элемента: {0}", "Unknown item type: {0}", "未知的项目类型：{0}"),
        ["items.bad_id"] = E("Недопустимый идентификатор", "Invalid identifier", "无效的标识符"),
        ["items.bad_id_value"] = E("Недопустимый идентификатор: {0}", "Invalid identifier: {0}", "无效的标识符：{0}"),
        ["list.not_found"] = E("Список «{0}» не найден", "List \"{0}\" not found", "未找到列表“{0}”"),
        ["list.ambiguous"] = E("Идентификатор «{0}» есть в нескольких типах списков", "Identifier \"{0}\" exists in several list types",
            "标识符“{0}”存在于多种列表类型中"),
        ["strategy.not_found_engine"] = E("Стратегия «{0}» для движка {1} не найдена", "Strategy \"{0}\" for engine {1} not found",
            "未找到引擎 {1} 的策略“{0}”"),
        ["strategy.not_found"] = E("Стратегия «{0}» не найдена", "Strategy \"{0}\" not found", "未找到策略“{0}”"),
        ["strategy.unreadable"] = E("Не удалось прочитать файл стратегии", "Could not read the strategy file", "无法读取策略文件"),
        ["strategy.unreadable_id"] = E("Не удалось прочитать файл стратегии «{0}» (нет файла или больше 64 КиБ)",
            "Could not read the file of strategy \"{0}\" (missing or larger than 64 KiB)", "无法读取策略“{0}”的文件（文件不存在或超过 64 KiB）"),
        ["strategy.bad_user_id"] = E("Имя своей стратегии должно начинаться с «user-» и содержать только латиницу, цифры, «.», «_», «-»",
            "The name of your own strategy must start with \"user-\" and contain only Latin letters, digits, \".\", \"_\", \"-\"",
            "自定义策略名称必须以“user-”开头，且只能包含拉丁字母、数字、“.”、“_”、“-”"),
        ["strategy.too_large"] = E("Текст стратегии больше 64 КиБ", "The strategy text is larger than 64 KiB", "策略文本超过 64 KiB"),
        ["strategy.save_failed"] = E("Не удалось сохранить стратегию", "Could not save the strategy", "无法保存策略"),
        ["strategy.delete_only_user"] = E("Удалять можно только свои стратегии (с префиксом «user-»)",
            "Only your own strategies (prefix \"user-\") can be deleted", "只能删除自定义策略（前缀为“user-”）"),
        ["strategy.active"] = E("Стратегия «{0}» сейчас выбрана. Сначала выберите другую.",
            "Strategy \"{0}\" is selected now. Choose another one first.", "策略“{0}”当前已选中。请先选择其他策略。"),
        ["strategy.user_not_found"] = E("Своя стратегия «{0}» не найдена", "Own strategy \"{0}\" not found", "未找到自定义策略“{0}”"),
        ["strategy.no_strategy"] = E("Не выбрана стратегия", "No strategy is selected", "未选择策略"),
        ["strategy.no_strategy_winws2"] = E("Не выбрана стратегия для winws2", "No strategy is selected for winws2", "未为 winws2 选择策略"),
        ["strategy.empty"] = E("Стратегия «{0}» не содержит ни одной опции", "Strategy \"{0}\" contains no options", "策略“{0}”不包含任何选项"),
        ["user.only_ids"] = E("Доступны только user-hosts, user-hosts-exclude, user-ipset, user-ipset-exclude",
            "Only user-hosts, user-hosts-exclude, user-ipset, user-ipset-exclude are available",
            "仅可使用 user-hosts、user-hosts-exclude、user-ipset、user-ipset-exclude"),
        ["user.too_large"] = E("Список больше 1 МиБ", "The list is larger than 1 MiB", "列表超过 1 MiB"),
        ["user.invalid_entries"] = E("Неверных строк: {0}. Исправьте их и сохраните снова.", "Invalid lines: {0}. Fix them and save again.",
            "无效行数：{0}。请修正后重新保存。"),
        ["user.save_failed"] = E("Не удалось сохранить список", "Could not save the list", "无法保存列表"),
        ["mode.bad"] = E("Режим должен быть whitelist или blacklist", "The mode must be whitelist or blacklist", "模式必须为 whitelist 或 blacklist"),
        ["engine.bad"] = E("Движок должен быть winws или winws2", "The engine must be winws or winws2", "引擎必须为 winws 或 winws2"),

        /* ---------- generator ---------- */
        ["gen.placeholder_in_token"] = E("Плейсхолдер {0} должен быть отдельным словом, а не частью «{1}»",
            "Placeholder {0} must be a separate word, not part of \"{1}\"", "占位符 {0} 必须是单独的词，而不能是“{1}”的一部分"),
        ["gen.unknown_placeholder"] = E("Неизвестный плейсхолдер {0} в стратегии", "Unknown placeholder {0} in the strategy", "策略中存在未知占位符 {0}"),
        ["gen.bad_placeholder_id"] = E("Недопустимый идентификатор в {0}", "Invalid identifier in {0}", "{0} 中的标识符无效"),
        ["gen.dependency_not_declared"] = E("Элемент «{0}» не объявлен в зависимостях стратегии",
            "Item \"{0}\" is not declared in the dependencies of the strategy", "项目“{0}”未在策略的依赖中声明"),
        ["gen.item_not_installed"] = E("Стратегии нужен элемент «{0}» ({1}), но он не установлен",
            "The strategy needs item \"{0}\" ({1}), but it is not installed", "策略需要项目“{0}”（{1}），但它未安装"),
        ["gen.unclosed_placeholder"] = E("Незакрытый плейсхолдер в «{0}»", "Unclosed placeholder in \"{0}\"", "“{0}”中的占位符未闭合"),
        ["gen.game_item_not_installed"] = E("Игровому фильтру нужен элемент «{0}» (bin), но он не установлен",
            "The game filter needs item \"{0}\" (bin), but it is not installed", "游戏过滤器需要项目“{0}”（bin），但它未安装"),
        ["gen.autohostlist_dir"] = E("Файл автолиста в --{0} должен лежать в {1}", "The auto list file of --{0} must be in {1}",
            "--{0} 的自动列表文件必须位于 {1}"),
        ["gen.bad_value"] = E("Неверное значение «{0}»", "Invalid value \"{0}\"", "无效的值“{0}”"),
        ["gen.inline_lua"] = E("Встроенный Lua-код в --lua-init не разрешён, укажите файл: --lua-init=@<файл>",
            "Inline Lua code in --lua-init is not allowed, give a file: --lua-init=@<file>", "--lua-init 中不允许内联 Lua 代码，请指定文件：--lua-init=@<文件>"),
        ["gen.lua_dir"] = E("Файл «{0}» в --lua-init должен лежать в каталоге Lua zaprett", "File \"{0}\" of --lua-init must be in a zaprett Lua folder",
            "--lua-init 的文件“{0}”必须位于 zaprett 的 Lua 目录中"),
        ["gen.path_outside"] = E("Файл «{0}» в опции --{1} находится вне каталогов zaprett", "File \"{0}\" of option --{1} is outside the zaprett folders",
            "选项 --{1} 的文件“{0}”位于 zaprett 目录之外"),
        ["gen.lists_not_found"] = E("Включённые списки не найдены: {0}. Установите их или выключите в настройках.",
            "Enabled lists not found: {0}. Install them or switch them off in the settings.", "未找到已启用的列表：{0}。请安装它们或在设置中关闭。"),
        ["gen.not_an_option"] = E("«{0}» — не опция: значение пишется через «=» (--опция=значение)",
            "\"{0}\" is not an option: write the value with \"=\" (--option=value)", "“{0}”不是选项：值应使用“=”书写（--选项=值）"),
        ["gen.ambiguous_option"] = E("Сокращение «--{0}» подходит к нескольким опциям движка {1}, напишите имя полностью",
            "The abbreviation \"--{0}\" matches several options of engine {1}, write the full name", "缩写“--{0}”匹配引擎 {1} 的多个选项，请写出完整名称"),
        ["gen.unknown_option"] = E("Движок {0} не знает опцию «--{1}»", "Engine {0} does not know option \"--{1}\"", "引擎 {0} 不认识选项“--{1}”"),
        ["gen.option_no_value"] = E("Опция --{0} не принимает значения: «{1}»", "Option --{0} takes no value: \"{1}\"", "选项 --{0} 不接受值：“{1}”"),
        ["gen.option_needs_value"] = E("Опции --{0} нужно значение: --{0}=значение", "Option --{0} needs a value: --{0}=value",
            "选项 --{0} 需要值：--{0}=值"),
        ["gen.bad_port_filter"] = E("Неверный фильтр портов в стратегии", "Invalid port filter in the strategy", "策略中的端口过滤器无效"),

        /* ---------- presets and wizard ---------- */
        ["presets.missing_path"] = E("Файл пресетов не найден или повреждён: {0}", "The presets file is missing or damaged: {0}", "预设文件缺失或已损坏：{0}"),
        ["presets.missing"] = E("Файл пресетов не найден или повреждён", "The presets file is missing or damaged", "预设文件缺失或已损坏"),
        ["wizard.no_services"] = E("Укажите хотя бы один сервис", "Choose at least one service", "请至少选择一个服务"),
        ["wizard.bad_ref"] = E("Неверный сервис «{0}»: ожидается <сервис> или <сервис>:<вариант>",
            "Invalid service \"{0}\": <service> or <service>:<variant> is expected", "无效的服务“{0}”：应为 <服务> 或 <服务>:<变体>"),
        ["wizard.unknown_service"] = E("Сервис «{0}» не найден в пресетах", "Service \"{0}\" not found in the presets", "预设中未找到服务“{0}”"),
        ["wizard.unknown_variant"] = E("У сервиса «{0}» нет варианта «{1}»", "Service \"{0}\" has no variant \"{1}\"", "服务“{0}”没有变体“{1}”"),
        ["wizard.variant_conflict"] = E("Сервис «{0}» указан с разными вариантами", "Service \"{0}\" is given with different variants",
            "服务“{0}”被指定了不同的变体"),
        ["wizard.nothing_in_set"] = E("Для сервиса «{0}» нет ни списков, ни подписок", "Service \"{0}\" has neither lists nor subscriptions",
            "服务“{0}”既没有列表也没有订阅"),
        ["wizard.all_skipped"] = E("Выбранные сервисы нельзя включить: обход для них не работает",
            "The chosen services cannot be switched on: the bypass does not work for them", "无法启用所选服务：绕过对它们无效"),
        ["wizard.items_missing"] = E("Не найдены списки или подписки пресета: {0}", "Lists or subscriptions of the preset not found: {0}",
            "未找到预设的列表或订阅：{0}"),

        /* ---------- subscriptions ---------- */
        ["src.bad_type"] = E("Тип подписки: list, list_exclude, ipset или ipset_exclude",
            "Subscription type: list, list_exclude, ipset or ipset_exclude", "订阅类型：list、list_exclude、ipset 或 ipset_exclude"),
        ["src.bad_url"] = E("Ссылка подписки должна начинаться с https:// и не содержать пробелов",
            "The subscription link must start with https:// and contain no spaces", "订阅链接必须以 https:// 开头且不能包含空格"),
        ["src.bad_title"] = E("Название — строка до 128 символов", "The title is a string of up to 128 characters", "标题是最多 128 个字符的字符串"),
        ["src.bad_number"] = E("{0}: целое число от {1} до {2}", "{0}: a whole number from {1} to {2}", "{0}：{1} 到 {2} 之间的整数"),
        ["src.bad_name"] = E("Имя подписки: только a-z, 0-9 и «_», до 32 символов",
            "Subscription name: only a-z, 0-9 and \"_\", up to 32 characters", "订阅名称：仅限 a-z、0-9 和“_”，最多 32 个字符"),
        ["src.bad_name_short"] = E("Недопустимое имя подписки", "Invalid subscription name", "无效的订阅名称"),
        ["src.save_failed"] = E("Не удалось сохранить подписку", "Could not save the subscription", "无法保存订阅"),
        ["src.move_failed"] = E("Не удалось перенести подписку в списки нового типа", "Could not move the subscription to the lists of the new type",
            "无法将订阅移到新类型的列表中"),
        ["src.not_found"] = E("Подписка «{0}» не найдена", "Subscription \"{0}\" not found", "未找到订阅“{0}”"),
        ["src.delete_failed"] = E("Не удалось удалить подписку", "Could not delete the subscription", "无法删除订阅"),
        ["src.nothing_to_update"] = E("Нет подписок для обновления", "No subscriptions to update", "没有需要更新的订阅"),
        ["src.progress_download"] = E("Загрузка подписок: {0} шт.", "Downloading subscriptions: {0}", "正在下载订阅：{0} 个"),
        ["src.progress_process"] = E("Обработка {0}", "Processing {0}", "正在处理 {0}"),
        ["src.log_updated"] = E("подписка {0}: обновлена, записей {1}", "subscription {0}: updated, {1} entries", "订阅 {0}：已更新，{1} 条"),
        ["src.log_unchanged"] = E("подписка {0}: без изменений, записей {1}", "subscription {0}: unchanged, {1} entries", "订阅 {0}：无变化，{1} 条"),
        ["src.update_failed"] = E("Не удалось обновить: {0}", "Could not update: {0}", "无法更新：{0}"),
        ["src.failed_item"] = E("{0} ({1})", "{0} ({1})", "{0}（{1}）"),
        ["src.download_failed"] = E("{0}. {1}", "{0}. {1}", "{0}。{1}"),
        ["src.err.too_few_entries"] = E("в загруженном списке слишком мало записей — похоже на обрыв или заглушку, оставлен прежний файл",
            "the downloaded list has too few entries (a cut download or a stub?), the previous file is kept", "下载的列表条目过少（下载中断或占位页？），保留原文件"),
        ["src.err.bad_content"] = E("слишком много неверных строк — оставлен прежний файл", "too many invalid lines, the previous file is kept",
            "无效行过多，保留原文件"),
        ["src.err.too_large"] = E("файл больше 16 МиБ — загрузка прервана, оставлен прежний файл",
            "the file is larger than 16 MiB, the download was stopped and the previous file is kept", "文件超过 16 MiB，已停止下载并保留原文件"),
        ["src.err.no_space"] = E("недостаточно места на диске — оставлен прежний файл", "not enough disk space, the previous file is kept",
            "磁盘空间不足，保留原文件"),
        ["src.err.write_failed"] = E("не удалось записать файл — оставлен прежний файл", "could not write the file, the previous file is kept",
            "无法写入文件，保留原文件"),
        ["src.err.invalid_source"] = E("неверные настройки подписки (тип или ссылка)", "invalid subscription settings (type or link)",
            "订阅设置无效（类型或链接）"),

        /* ---------- repository ---------- */
        ["repo.id_note"] = E("в манифесте указан id «{0}»", "the manifest gives id \"{0}\"", "清单中给出的 id 为“{0}”"),
        ["repo.progress_index"] = E("Загрузка индекса репозитория: {0}", "Downloading the repository index: {0}", "正在下载仓库索引：{0}"),
        ["repo.index_too_large"] = E("Индекс репозитория больше 2 МиБ — загрузка прервана", "The repository index is larger than 2 MiB, the download was stopped",
            "仓库索引超过 2 MiB，已停止下载"),
        ["repo.index_download_failed"] = E("Не удалось загрузить индекс репозитория ({0}). {1}", "Could not download the repository index ({0}). {1}",
            "无法下载仓库索引（{0}）。{1}"),
        ["repo.bad_index"] = E("Индекс репозитория повреждён или имеет неизвестный формат", "The repository index is damaged or in an unknown format",
            "仓库索引已损坏或格式未知"),
        ["repo.progress_manifests"] = E("Загрузка манифестов: {0} шт.", "Downloading manifests: {0}", "正在下载清单：{0} 个"),
        ["repo.cache_failed"] = E("Не удалось сохранить кэш репозитория", "Could not save the repository cache", "无法保存仓库缓存"),
        ["repo.progress_index_done"] = E("Индекс загружен: {0} элементов, ошибок {1}", "Index downloaded: {0} items, {1} errors",
            "索引已下载：{0} 个项目，{1} 个错误"),
        ["repo.write_failed"] = E("Не удалось записать {0}", "Could not write {0}", "无法写入 {0}"),
        ["repo.manifest_write_failed"] = E("Не удалось записать манифест {0}", "Could not write the manifest of {0}", "无法写入 {0} 的清单"),
        ["repo.unsupported"] = E("Элемент «{0}» ({1}) не поддерживается в zaprett", "Item \"{0}\" ({1}) is not supported by zaprett", "zaprett 不支持项目“{0}”（{1}）"),
        ["repo.not_in_repo"] = E("Элемент «{0}» не найден в индексе репозитория", "Item \"{0}\" not found in the repository index", "仓库索引中未找到项目“{0}”"),
        ["repo.ambiguous"] = E("Идентификатор «{0}» встречается в нескольких типах: {1}", "Identifier \"{0}\" is used by several types: {1}",
            "标识符“{0}”属于多种类型：{1}"),
        ["repo.dep_not_found"] = E("Зависимость элемента «{0}» не найдена в индексе: {1}", "A dependency of item \"{0}\" is not in the index: {1}",
            "索引中找不到项目“{0}”的依赖：{1}"),
        ["repo.all_installed"] = E("Всё уже установлено и обновлено", "Everything is installed and up to date", "所有项目均已安装并为最新"),
        ["repo.progress_files"] = E("Загрузка файлов: {0} шт.", "Downloading files: {0}", "正在下载文件：{0} 个"),
        ["repo.file_too_large"] = E("Файл «{0}» больше 32 МиБ — загрузка прервана", "File \"{0}\" is larger than 32 MiB, the download was stopped",
            "文件“{0}”超过 32 MiB，已停止下载"),
        ["repo.download_failed"] = E("Не удалось скачать «{0}»: {1}. {2}", "Could not download \"{0}\": {1}. {2}", "无法下载“{0}”：{1}。{2}"),
        ["repo.sha_mismatch"] = E("Контрольная сумма «{0}» не совпала с манифестом — файл отклонён",
            "The checksum of \"{0}\" does not match the manifest, the file was rejected", "“{0}”的校验和与清单不符，文件已被拒绝"),
        ["repo.no_space"] = E("Недостаточно места на диске: нужно {0} КиБ, свободно {1} КиБ", "Not enough disk space: {0} KiB needed, {1} KiB free",
            "磁盘空间不足：需要 {0} KiB，可用 {1} KiB"),
        ["repo.progress_install"] = E("Установка {0}", "Installing {0}", "正在安装 {0}"),
        ["repo.log_installed"] = E("установлен {0} {1} версии {2}", "installed {0} {1} version {2}", "已安装 {0} {1}，版本 {2}"),
        ["repo.readonly_source"] = E("«{0}» — подписка по ссылке; удаляется через sources.delete",
            "\"{0}\" is a subscription by link; delete it with sources.delete", "“{0}”是链接订阅；请用 sources.delete 删除"),
        ["repo.readonly_item"] = E("Элемент «{0}» входит в состав программы или является пользовательским и не удаляется",
            "Item \"{0}\" is part of the program or a user item and cannot be removed", "项目“{0}”属于程序自带或用户项目，不能删除"),
        ["repo.not_installed"] = E("Элемент «{0}» не установлен", "Item \"{0}\" is not installed", "项目“{0}”未安装"),
        ["repo.ambiguous_installed"] = E("Идентификатор «{0}» установлен в нескольких типах", "Identifier \"{0}\" is installed in several types",
            "标识符“{0}”以多种类型安装"),
        ["repo.in_use"] = E("Элемент «{0}» нужен стратегиям: {1}", "Item \"{0}\" is needed by strategies: {1}", "以下策略需要项目“{0}”：{1}"),
        ["repo.active"] = E("Элемент «{0}» сейчас используется в настройках. Сначала отключите его.",
            "Item \"{0}\" is used in the settings now. Switch it off first.", "项目“{0}”正在设置中使用。请先关闭它。"),
        ["repo.log_removed"] = E("удалён {0} {1}", "removed {0} {1}", "已删除 {0} {1}"),
        ["repo.not_fetched"] = E("Индекс репозитория не загружен", "The repository index has not been downloaded", "仓库索引尚未下载"),
        ["repo.not_installed_or_missing"] = E("Элемент «{0}» не установлен или отсутствует в репозитории",
            "Item \"{0}\" is not installed or missing from the repository", "项目“{0}”未安装或仓库中不存在"),
        ["repo.no_updates"] = E("Обновлений нет", "No updates", "没有更新"),
        ["repo.autoupdate_off"] = E("Автообновление элементов репозитория выключено", "Automatic update of repository items is off",
            "仓库项目的自动更新已关闭"),
        ["repo.autoupdate_done"] = E("Автообновление выполнено", "Automatic update completed", "自动更新已完成"),

        /* ---------- jobs ---------- */
        ["job.interrupted"] = E("Задача прервалась (служба была перезапущена)", "The job was interrupted (the service restarted)",
            "任务已中断（服务已重启）"),
        ["job.busy"] = E("Уже выполняется другая задача. Дождитесь её завершения или отмените её.",
            "Another job is running. Wait for it to finish or cancel it.", "另一个任务正在运行。请等待其完成或取消它。"),
        ["job.busy_named"] = E("Уже выполняется другая задача («{0}»). Дождитесь её завершения или отмените её.",
            "Another job is running (\"{0}\"). Wait for it to finish or cancel it.", "另一个任务正在运行（“{0}”）。请等待其完成或取消它。"),
        ["job.starting"] = E("Задача запускается…", "The job is starting…", "任务正在启动…"),
        ["job.log_start"] = E("Запуск задачи {0}", "Starting job {0}", "启动任务 {0}"),
        ["job.running"] = E("Выполняется…", "Running…", "正在运行…"),
        ["job.cancelled_short"] = E("Отменено", "Cancelled", "已取消"),
        ["job.cancelled"] = E("Задача отменена", "The job was cancelled", "任务已取消"),
        ["job.done"] = E("Готово", "Done", "完成"),
        ["job.log_result"] = E("Итог: {0}", "Result: {0}", "结果：{0}"),
        ["job.log_result_msg"] = E("Итог: {0} — {1}", "Result: {0} — {1}", "结果：{0} — {1}"),
        ["job.no_job"] = E("Нет выполняющейся задачи", "No job is running", "没有正在运行的任务"),
        ["job.cancelling"] = E("Отмена задачи…", "Cancelling the job…", "正在取消任务…"),
        ["job.log_cancel"] = E("Запрошена отмена задачи", "Job cancellation requested", "已请求取消任务"),
        ["job.log_trimmed"] = E("[…журнал обрезан…]", "[…log trimmed…]", "[…日志已截断…]"),

        /* ---------- checks: errors ---------- */
        ["probe.err.too_small"] = E("ответ слишком короткий (обрыв или заглушка)", "the answer is too short (cut off or a stub)",
            "响应过短（被截断或是占位页）"),
        ["probe.err.http_error"] = E("сервер вернул ошибку HTTP", "the server returned an HTTP error", "服务器返回了 HTTP 错误"),
        ["probe.err.timeout"] = E("нет ответа (таймаут)", "no answer (timeout)", "无响应（超时）"),
        ["probe.err.reset"] = E("соединение сброшено", "the connection was reset", "连接被重置"),
        ["probe.err.tls_cert"] = E("подменённый сертификат", "a forged certificate", "证书被伪造"),
        ["probe.err.tls_error"] = E("ошибка TLS (обрыв рукопожатия)", "TLS error (the handshake broke off)", "TLS 错误（握手中断）"),
        ["probe.err.connect_failed"] = E("не удалось подключиться", "could not connect", "无法连接"),
        ["probe.err.local_error"] = E("ошибка записи во временный файл", "error writing a temporary file", "写入临时文件出错"),
        ["probe.err.failed"] = E("ошибка загрузки", "download error", "下载错误"),
        ["probe.err.too_large"] = E("файл больше допустимого размера", "the file is larger than allowed", "文件超过允许的大小"),
        ["probe.err.unknown"] = E("ошибка", "error", "错误"),

        /* ---------- watchdog, probe, monitor ---------- */
        ["health.unknown_service"] = E("Сервис «{0}» не найден в пресетах", "Service \"{0}\" not found in the presets", "预设中未找到服务“{0}”"),
        ["health.write_failed"] = E("Не удалось записать {0}", "Could not write {0}", "无法写入 {0}"),
        ["health.ensure_failed"] = E("Движок не работал, и запустить его не удалось. Подробности: zaprett check",
            "The engine was not running and could not be started. Details: zaprett check", "引擎未运行且无法启动。详情：zaprett check"),
        ["health.log_ensure_failed"] = E("сторож: движок не работал, запустить его не удалось: {0}",
            "watchdog: the engine was not running and could not be started: {0}", "看门狗：引擎未运行且无法启动：{0}"),
        ["health.log_ensure_started"] = E("сторож: движок не работал — запущен заново (pid {0})",
            "watchdog: the engine was not running and has been started again (pid {0})", "看门狗：引擎未运行，已重新启动（pid {0}）"),
        ["health.log_fw_applied"] = E("сторож: правила брандмауэра zaprett не было — применено заново",
            "watchdog: the zaprett firewall rule was missing and has been applied again", "看门狗：缺少 zaprett 防火墙规则，已重新应用"),
        ["health.progress_probe"] = E("Проверка сервисов: {0}, адресов: {1}", "Checking services: {0}, addresses: {1}", "正在检查服务：{0} 个，地址：{1} 个"),
        ["health.log_service"] = E("{0}: доступно {1} из {2}", "{0}: {1} of {2} reachable", "{0}：{2} 个中 {1} 个可访问"),
        ["health.probe_result"] = E("Доступно {0} из {1} адресов", "{0} of {1} addresses reachable", "{1} 个地址中 {0} 个可访问"),
        ["health.log_degraded"] = E("монитор: доступно {0} из {1} адресов, неудачных проверок подряд: {2} — состояние degraded",
            "monitor: {0} of {1} addresses reachable, {2} failed checks in a row — state degraded", "监控：{1} 个地址中 {0} 个可访问，连续失败检查 {2} 次 — 状态 degraded"),
        ["health.log_repair_started"] = E("монитор: запущен быстрый автоподбор стратегии (задача {0})",
            "monitor: a quick automatic strategy selection was started (job {0})", "监控：已启动快速自动选择策略（任务 {0}）"),
        ["health.log_repair_conflict"] = E("монитор: автоподбор не запущен — обходу мешает другая программа: {0}",
            "monitor: the automatic selection was not started — another program blocks the bypass: {0}",
            "监控：未启动自动选择——另一个程序妨碍绕过：{0}"),
        ["test.log_conflict"] = E("подбор стратегии идёт при мешающей программе, результаты могут быть неверными: {0}",
            "the strategy selection runs while another program interferes, the results may be wrong: {0}",
            "策略选择在有干扰程序的情况下进行，结果可能不准确：{0}"),
        ["log.install_id_write_failed"] = E("не удалось записать идентификатор установки {0}", "could not write the installation id {0}",
            "无法写入安装标识 {0}"),
        ["log.conflicts_scan_failed"] = E("не удалось проверить конфликтующие программы: {0}",
            "could not check for conflicting programs: {0}", "无法检查冲突程序：{0}"),
        ["health.log_recheck"] = E("монитор: мешавшая программа закрыта — внеочередная проверка доступности",
            "monitor: the interfering program is gone — an extra availability check",
            "监控：干扰程序已关闭——额外检查一次可用性"),
        ["health.log_recheck_failed"] = E("монитор: внеочередная проверка не удалась: {0}", "monitor: the extra check failed: {0}",
            "监控：额外检查失败：{0}"),
        ["health.log_repair_unknown"] = E("монитор: автоподбор отложен — не удалось проверить, не мешает ли другая программа",
            "monitor: the automatic selection is put off — could not check whether another program interferes",
            "监控：自动选择已推迟——无法检查是否有其他程序干扰"),
        ["health.log_repair_failed"] = E("монитор: автоподбор не запущен: {0}", "monitor: the automatic selection was not started: {0}",
            "监控：未能启动自动选择：{0}"),

        /* ---------- automatic selection ---------- */
        ["test.no_strategies"] = E("Нет установленных стратегий для проверки", "No installed strategies to check", "没有可检查的已安装策略"),
        ["test.no_targets"] = E("Нет целей для проверки: включите хотя бы один список доменов или сервис в быстрой настройке",
            "Nothing to check: switch on at least one domain list or a service in the quick setup", "没有可检查的目标：请在快速设置中至少启用一个域名列表或服务"),
        ["test.log_start"] = E("автоподбор: {0} стратегий, {1} целей, режим {2}", "automatic selection: {0} strategies, {1} targets, mode {2}",
            "自动选择：{0} 个策略，{1} 个目标，模式 {2}"),
        ["test.log_start_reason"] = E("автоподбор: {0} стратегий, {1} целей, режим {2} ({3})",
            "automatic selection: {0} strategies, {1} targets, mode {2} ({3})", "自动选择：{0} 个策略，{1} 个目标，模式 {2}（{3}）"),
        ["test.progress_prepare"] = E("Подготовка проверки без отключения обхода", "Preparing a check without switching the bypass off",
            "正在准备在不关闭绕过的情况下进行检查"),
        ["test.log_no_isolation"] = E("автоподбор: проверка без отключения обхода невозможна ({0}), движок будет остановлен на время подбора",
            "automatic selection: checking without switching the bypass off is impossible ({0}), the engine will be stopped during the selection",
            "自动选择：无法在不关闭绕过的情况下检查（{0}），选择期间将停止引擎"),
        ["test.job_no_isolation"] = E("Проверка без отключения обхода невозможна ({0}): обход на время подбора будет выключен",
            "Checking without switching the bypass off is impossible ({0}): the bypass will be off during the selection",
            "无法在不关闭绕过的情况下检查（{0}）：选择期间将关闭绕过"),
        ["test.progress_baseline"] = E("Базовая проверка без обхода: {0} целей", "Baseline check without the bypass: {0} targets",
            "不使用绕过的基准检查：{0} 个目标"),
        ["test.log_baseline"] = E("Без обхода доступно {0} из {1}", "Without the bypass {0} of {1} are reachable", "不使用绕过时 {1} 个中 {0} 个可访问"),
        ["test.progress_strategy"] = E("Стратегия {0} из {1}: {2}", "Strategy {0} of {1}: {2}", "策略 {0}/{1}：{2}"),
        ["test.log_candidate"] = E("{0}: {1} {2}/{3}", "{0}: {1} {2}/{3}", "{0}：{1} {2}/{3}"),
        ["test.log_applied"] = E("автоподбор: применена стратегия {0} (лучше исходной {1})",
            "automatic selection: strategy {0} applied (better than the original {1})", "自动选择：已应用策略 {0}（优于原策略 {1}）"),
        ["test.job_applied"] = E("Применена стратегия {0}", "Strategy {0} applied", "已应用策略 {0}"),
        ["test.progress_restart_new"] = E("Запуск с новой стратегией", "Starting with the new strategy", "使用新策略启动"),
        ["test.progress_remove_instance"] = E("Снятие проверочного экземпляра", "Removing the check instance", "正在移除检查实例"),
        ["test.progress_restore"] = E("Возврат исходной стратегии", "Returning the original strategy", "正在恢复原策略"),
        ["test.failed"] = E("Ошибка автоподбора: {0}", "Automatic selection error: {0}", "自动选择出错：{0}"),
        ["test.best"] = E("Лучшая стратегия: {0}", "Best strategy: {0}", "最佳策略：{0}"),
        ["test.best_applied"] = E("Лучшая стратегия: {0}; применена вместо {1}", "Best strategy: {0}; applied instead of {1}",
            "最佳策略：{0}；已替代 {1} 应用"),
        ["test.none_better"] = E("Ни одна стратегия не улучшила доступность", "No strategy improved the reachability", "没有策略提高可访问性"),
        ["test.engine_failed"] = E("Движок не запустился с этой стратегией", "The engine did not start with this strategy", "引擎无法以此策略启动"),
        ["test.udp_skipped"] = E("проверка UDP/QUIC не изолируется — цель пропущена", "UDP/QUIC checks cannot be isolated — the target was skipped",
            "UDP/QUIC 检查无法隔离 — 已跳过该目标"),
        ["test.log_restore_failed"] = E("автоподбор: не удалось вернуть исходное состояние: {0}",
            "automatic selection: could not return to the original state: {0}", "自动选择：无法恢复原始状态：{0}"),
        ["test.restore_failed"] = E("Не удалось вернуть исходное состояние после автоподбора: {0}",
            "Could not return to the original state after the automatic selection: {0}", "自动选择后无法恢复原始状态：{0}"),
        ["test.not_running"] = E("Автоподбор не выполняется", "No automatic selection is running", "没有正在进行的自动选择"),
        ["test.running_apply"] = E("Идёт автоподбор. Дождитесь окончания или остановите его.", "An automatic selection is running. Wait for it to finish or stop it.",
            "正在进行自动选择。请等待其完成或停止它。"),
        ["test.write_failed"] = E("Не удалось записать {0}", "Could not write {0}", "无法写入 {0}"),

        /* ---------- diagnosis ---------- */
        ["diagnose.reason.stub_address"] = E("системный DNS вернул адрес-заглушку", "the system DNS returned a stub address", "系统 DNS 返回了占位地址"),
        ["diagnose.reason.no_system_answer"] = E("системный DNS не знает этот домен, а DNS-over-HTTPS знает",
            "the system DNS does not know this domain, DNS-over-HTTPS does", "系统 DNS 不认识此域名，而 DNS-over-HTTPS 认识"),
        ["diagnose.reason.address_differs"] = E("системный DNS дал адрес, которого нет в ответе DNS-over-HTTPS, и сайт по нему не открылся",
            "the system DNS gave an address missing from the DNS-over-HTTPS answer, and the site did not open at it",
            "系统 DNS 给出的地址不在 DNS-over-HTTPS 的应答中，且该地址无法打开网站"),
        ["diagnose.reason.dns_failed"] = E("домен не удалось разрешить ни системным DNS, ни через DNS-over-HTTPS",
            "the domain could not be resolved by the system DNS nor by DNS-over-HTTPS", "系统 DNS 和 DNS-over-HTTPS 都无法解析该域名"),
        ["diagnose.reason.http_451"] = E("сервер ответил кодом 451 (недоступно по юридическим причинам)",
            "the server answered 451 (unavailable for legal reasons)", "服务器返回 451（因法律原因不可用）"),
        ["diagnose.reason.forged_certificate"] = E("вместо сайта отвечает чужой сертификат — заглушка провайдера",
            "a foreign certificate answers instead of the site — a provider stub", "网站被他人的证书替代应答 — 运营商占位页"),
        ["diagnose.reason.tcp_failed"] = E("TCP-соединение с настоящим адресом сайта не устанавливается",
            "no TCP connection to the real address of the site", "无法与网站真实地址建立 TCP 连接"),
        ["diagnose.reason.tcp_ok_fetch_failed"] = E("соединение с адресом из DNS-over-HTTPS есть, но загрузка не удалась",
            "the address from DNS-over-HTTPS accepts connections, but the download failed", "可以连接 DNS-over-HTTPS 给出的地址，但下载失败"),
        ["diagnose.reason.tls_error"] = E("соединение есть, но TLS-рукопожатие обрывается", "connected, but the TLS handshake breaks off",
            "已连接，但 TLS 握手中断"),
        ["diagnose.reason.reset"] = E("соединение есть, но сбрасывается", "connected, but the connection is reset", "已连接，但连接被重置"),
        ["diagnose.reason.timeout"] = E("соединение есть, но ответа нет", "connected, but there is no answer", "已连接，但没有响应"),
        ["diagnose.reason.tcp_not_checked"] = E("проверка TCP не выполнена", "the TCP check was not done", "未进行 TCP 检查"),
        ["diagnose.download_error"] = E("ошибка загрузки: {0}", "download error: {0}", "下载错误：{0}"),
        ["diagnose.site_opens"] = E("сайт открывается", "the site opens", "网站可以打开"),
        ["diagnose.throttle"] = E("данные идут и замирают на {0} байт — похоже на замедление",
            "data flows and freezes at {0} bytes — looks like throttling", "数据传输在 {0} 字节处停滞 — 疑似限速"),
        ["diagnose.detail"] = E("{0} (системный DNS: {1}; DoH: {2})", "{0} (system DNS: {1}; DoH: {2})", "{0}（系统 DNS：{1}；DoH：{2}）"),
        ["diagnose.no_answer"] = E("нет ответа", "no answer", "无应答"),
        ["diagnose.log_system_dns"] = E("диагностика: системный DNS для {0}: {1}", "diagnosis: system DNS for {0}: {1}", "诊断：{0} 的系统 DNS：{1}"),
        ["diagnose.log_doh"] = E("диагностика: DoH для {0}: {1}", "diagnosis: DoH for {0}: {1}", "诊断：{0} 的 DoH：{1}"),
        ["diagnose.log_tcp"] = E("диагностика: TCP {0}:{1}: {2}", "diagnosis: TCP {0}:{1}: {2}", "诊断：TCP {0}:{1}：{2}"),
        ["diagnose.no_targets"] = E("Нет целей для проверки: включите сервис в быстрой настройке или укажите services",
            "Nothing to check: switch on a service in the quick setup or give services", "没有可检查的目标：请在快速设置中启用服务或指定 services"),
        ["diagnose.progress_dns"] = E("DNS: {0} адресов", "DNS: {0} addresses", "DNS：{0} 个地址"),
        ["diagnose.progress_pages"] = E("Загрузка страниц", "Downloading pages", "正在下载页面"),
        ["diagnose.progress_tcp"] = E("Проверка TCP: {0}", "TCP check: {0}", "TCP 检查：{0}"),
        ["diagnose.log_target"] = E("{0}: {1} — {2}", "{0}: {1} — {2}", "{0}：{1} — {2}"),
        ["diagnose.result"] = E("Итог: {0} ({1} адресов)", "Result: {0} ({1} addresses)", "结果：{0}（{1} 个地址）"),
    };
}
